export const MVD_THRESHOLD = 40
export const STRONG_THRESHOLD = 80

export const DEFAULT_HABITS = [
  {
    id: 'h1',
    name: 'Feet on floor by 7:15am',
    description: "Day's trajectory is set in the first 30 minutes",
    xp: 30,
    category: 'productivity',
    timeOfDay: 'morning',
    appliesTo: 'weekday',
    badDayVersion: 'Up by 7:30am',
    badDayXp: 15,
    sortOrder: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h1w',
    name: 'Out of bed by 8:30am',
    description: 'No alarm required, but no sleeping past 8:30',
    xp: 20,
    category: 'productivity',
    timeOfDay: 'morning',
    appliesTo: 'weekend',
    badDayVersion: 'Up by 9am',
    badDayXp: 10,
    sortOrder: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h2',
    name: "Write tomorrow's Top 3 before bed",
    description: "Eliminates morning decision paralysis. One task must be the thing you're avoiding.",
    xp: 25,
    category: 'productivity',
    timeOfDay: 'evening',
    appliesTo: 'both',
    badDayVersion: "Write 1 task — the one you're dodging",
    badDayXp: 15,
    sortOrder: 2,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h3',
    name: '90-min Deep Work block before noon',
    description: 'Phone in another room. No browser tabs except what you need. This is where the business gets built.',
    xp: 40,
    category: 'productivity',
    timeOfDay: 'morning',
    appliesTo: 'weekday',
    badDayVersion: '45 min, one task, no distractions',
    badDayXp: 25,
    sortOrder: 3,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h3w',
    name: '2-hour Saturday Build Block',
    description: 'Sanctioned tinkering time. Guilt-free, but bounded.',
    xp: 35,
    category: 'productivity',
    timeOfDay: 'morning',
    appliesTo: 'weekend',
    badDayVersion: '1-hour focused build session',
    badDayXp: 20,
    sortOrder: 3,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h4',
    name: 'Walk 20+ minutes',
    description: 'Clears decision fog. Keeps the 250-day walking goal alive.',
    xp: 25,
    category: 'health',
    timeOfDay: 'anytime',
    appliesTo: 'both',
    badDayVersion: '10 minutes around the block',
    badDayXp: 15,
    sortOrder: 4,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h5',
    name: 'Eat a real meal before noon',
    description: "Protein + anything. You can't make bold decisions on fumes.",
    xp: 20,
    category: 'health',
    timeOfDay: 'morning',
    appliesTo: 'both',
    badDayVersion: 'Protein shake or bar — 5 minutes',
    badDayXp: 10,
    sortOrder: 5,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h6',
    name: 'Hard shutdown at 6:30pm',
    description: 'Laptop closed, notifications off. Your wife gets predictable, present time.',
    xp: 30,
    category: 'relationship',
    timeOfDay: 'evening',
    appliesTo: 'weekday',
    badDayVersion: 'Close work tabs — Slack, n8n, email',
    badDayXp: 15,
    sortOrder: 6,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h7',
    name: 'No YouTube/AI after 10:30pm',
    description: 'This is the #1 thing stealing your morning. Late-night ideas cost 90 min of sleep.',
    xp: 30,
    category: 'health',
    timeOfDay: 'evening',
    appliesTo: 'both',
    badDayVersion: 'Phone charges in another room by 10:30',
    badDayXp: 20,
    sortOrder: 7,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h8',
    name: 'Lights out by 11:30pm',
    description: 'The keystone of the keystones. Protect sleep and habits 1–7 are 3x easier.',
    xp: 30,
    category: 'health',
    timeOfDay: 'evening',
    appliesTo: 'both',
    badDayVersion: 'Midnight hard ceiling',
    badDayXp: 15,
    sortOrder: 8,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h9',
    name: 'Strength training session',
    description: '3x/week target. 150 sessions/year goal. Pick any 3 of 5 weekdays.',
    xp: 35,
    category: 'health',
    timeOfDay: 'anytime',
    appliesTo: 'both',
    badDayVersion: '20-min bodyweight session at home',
    badDayXp: 20,
    sortOrder: 9,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h10',
    name: 'Friday Weekly Review (30 min)',
    description: "What shipped, what got avoided, Monday's Top 3.",
    xp: 30,
    category: 'productivity',
    timeOfDay: 'afternoon',
    appliesTo: 'weekday',
    badDayVersion: "15-min quick scan + Monday's #1 task",
    badDayXp: 15,
    sortOrder: 10,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'h11',
    name: 'Sunday Marriage Meeting',
    description: '30–60 min. Calendar review, one date planned, anything unresolved.',
    xp: 30,
    category: 'relationship',
    timeOfDay: 'evening',
    appliesTo: 'weekend',
    badDayVersion: '15-min calendar sync + one thing planned',
    badDayXp: 15,
    sortOrder: 11,
    active: true,
    createdAt: new Date().toISOString(),
  },
]
